version: '3'

services:
    app:
        container_name: chrisalopez1337/share-lgbt
        image: chrisalopez1337/share-lgbt:latest
        restart: always
        build: ./
        ports:
            - "80:3000"
            - "443:3000"
